### ISSUE TITLE
📚 [ Feat ] 회원가입 기능 구현

### ISSUE THREAD

**Issue by tkyoun0421** [12-Cookie/cookie-chat#1]
## 작업 내용
회원가입 기능 구현하기

## 유효성 검사 로직
이메일, 이름, 비밀번호, 비밀번호 확인 필드에 대한 유효성 검사를 수행

### 유효성 검사 시점
* input `focus out`시 해당 필드의 유효성 검사
* 회원가입 버튼 클릭 시 모든 필드의 유효성 검사

### 유효성 검사 패턴
모든 필드의 값은 빠짐없이 입력해야합니다.
이메일, 이름, 비밀번호, 비밀번호 확인 필드는 해당 조건의 유효성 조건을 통과해야합니다.

* 이메일: 이메일 형식
* 이름: 한글과 영문 사용 가능
* 비밀번호: 8~16자 영문 소/대문자, 숫자 사용가능
* 비밀번호 확인: 비밀번호와 일치

### 커스텀 에러 메세지
유효하지 않은 값일 경우, 각 에러에 맞는 에러 메세지를 보여주어야 합니다.

* (공통) 빈 값일 경우: "필수 정보입니다."
* (이메일) 유효하지 않은 값일 경우: "이메일 형식을 맞춰서 입력해주세요."
* (이름) 유효하지 않은 값일 경우: "이름 형식이 올바르지 않습니다."
* (비밀번호) 유효하지 않은 값일 경우: "8~16자 영문 소/대문자, 숫자를 사용하세요."
* (비밀번호 확인) 유효하지 않은 값일 경우: "비밀번호가 일치하지 않습니다."

## 완료 예상일
2023.08.31

## 하위 태스크
- [x] 이메일 유효성 검사
- [x] 비밀번호 유효성 검사
- [x] 이메일 유효성 검사
- [x] 페이지 접속시 이메일 오토포커스
- [x] 회원가입 된 데이터 Firebase DB에 저장
- [x] 리팩토링

**Comment by 2YH02** [comment]
혹시 이 이슈에서 파이어베이스를 통한 회원가입, 인증까지 구현하시는지 아니면 일단 필수 정보와 형식에 대한 유효성 검사만 우선 구현하시는 건지 알 수 있을까요?

**Comment by tkyoun0421** [comment]
> 혹시 이 이슈에서 파이어베이스를 통한 회원가입, 인증까지 구현하시는지 아니면 일단 필수 정보와 형식에 대한 유효성 검사만 우선 구현하시는 건지 알 수 있을까요?

일단은 유효성 검사 이후 완료되면 회원가입 인증까지 구현해 볼 생각입니다!

**Comment by 2YH02** [comment]
> 일단은 유효성 검사 이후 완료되면 회원가입 인증까지 구현해 볼 생각입니다! 아직 회원가입 인증 부분에 대한 지식이 없어서 공부를 좀 해봐야 할 것 같습니다

넵 답변 감사합니다! 화이팅!

**Comment by 2YH02** [comment]
만약 회원가입 완료되면 생성된 uid를 id로 하는 유저 데이터를 파이어베이스 스토어 저장하는 것도 만들면 좋을 거 같아요!

회원가입 완료 -> 파이어베이스 users 컬렉션 안에다가 생성된 uid를 이름으로 하는 문서 생성 -> 해당 문서의 필드 값으로 처음에 정한 데이터 구조대로 유저 데이터 생성 -> index.html로 페이지 이동

이런식으로 하면 좋을 것 같아요!
