### ISSUE TITLE
[채팅방 생성 기능]

### ISSUE THREAD

**Issue by joanShim** [12-Cookie/cookie-chat#16]
## 작업 내용
채팅방 생성

## 하위 태스크

- [ ] room 데이터 생성
- [ ] emoji 값 저장
- [ ] 컬러, 키워드 값 저장

**Comment by 2YH02** [comment]
기능 만드실 때 포크한 레포 동기화 시키신 다음에 pull로 가져오시면
main.js에 제가 이런 식으로 임시로 유저가 로그인했다고 가정하고 로컬스토리지에 데이터 넣어놨습니다.
```javascript
const user = {
  id: "xzIZIHffe8QpmF8GnBN6",
  email: "test@test.com",
  isLogin: "true",
  likes: ["sCBgQQYu52Au7HTdbq7g", "3v6iOUQhzX9WA1Qer4Ao"],
  name: "user1",
  phone: "010-1111-1111",
};

localStorage.setItem("user", JSON.stringify(user));
```
로그인이 기능 완성되기 전에 임시로 이 유저가 로그인했다고 가정하고 로컬스토리지에서 유저의 id를 가져와서
room 생성될 때 host 값으로 이 유저의 id 값을 넣으면 될 거 같아요!
