### ISSUE TITLE
:hammer: [ Fix ] mainPage.html a 태그 부모 버튼 태그의 전체 크기 상속받게 수정

### ISSUE THREAD

**Issue by tkyoun0421** [12-Cookie/cookie-chat#26]
## 작업 내용
mainPage.html a 태그 부모 버튼 태그의 전체 크기 상속받게 수정

## 완료 예상일
2023.09.04

## 하위 태스크
- [x] css 수정

**Comment by 2YH02** [comment]
와.. 저는 가끔씩 왜 안 눌리나 했는데 이거 때문이었군요 ㅠㅠ 찾아주셔서 감사합니다!
